### PR TITLE
Updates to data regulations page

### PR DESCRIPTION
**Pull request by bradhenslee**
Updates as per https://www.pivotaltracker.com/n/projects/2491136
FIGMA: https://www.figma.com/file/ql473qCtzbIMfDtb5na0X4/MindKind_UX_Flow?node-id=3208%3A13825

image

### CODE REVIEW

**Comment by bradhenslee** [comment]
This PR is part 1 to complete https://www.pivotaltracker.com/n/projects/2491136/stories/178717946/comments/225389022. 

Remaining changes will be made in a a part 2 branch later after document structuring work is complete.

**Review by carlosalvarado1988 — COMMENTED** [review]
image

Looking at the presentation - would you add ensure there is space between bullets ? :)

**Comment by bradhenslee** [comment]
> Looking at the presentation - would you add ensure there is space between bullets ? :)

Hmm. Deric has added this page to the "updates" section in Figma, and it's different as well--no bullets at all. 
https://www.figma.com/file/ql473qCtzbIMfDtb5na0X4/MindKind_UX_Flow?node-id=3208%3A13825

Lmk what you think I should follow -- I think the important thing is that our bullet styles are consistent across the site, so I don't want to go by the presentation markup :) 

 @carlosalvarado1988

**Comment by bradhenslee** [comment]
> > Looking at the presentation - would you add ensure there is space between bullets ? :)
> 
> Hmm. Deric has added this page to the "updates" section in Figma, and it's different as well--no bullets at all.
> https://www.figma.com/file/ql473qCtzbIMfDtb5na0X4/MindKind_UX_Flow?node-id=3208%3A13825
> 
> Lmk what you think I should follow -- I think the important thing is that our bullet styles are consistent across the site, so I don't want to go by the presentation markup :)

**Review by carlosalvarado1988 — COMMENTED** [review]
Agreed on styles dicussion, ready to merge after conflict is solved

**Comment by bradhenslee** [comment]
Looking to see if there is a text update. Will reopen PR when confirmed.

**Review by carlosalvarado1988 — APPROVED** [review]

**Pull request merged**
